## 任务7.3　使用`K-Means`算法进行客户分群

<center>
    <br>
    代码7-4　航空客户价值分析<code>K-Means</code>聚类
</center>

In [1]:
import numpy
# 导入 K-Means 聚类算法
from sklearn.cluster import KMeans
airline_scale = numpy.load('stash/airline_scale.npz')['arr_0']
# 确定聚类中心数量
k = 5
# 构建模型
kmeans_model = KMeans(n_clusters=k, n_jobs=4, random_state=0x6A1B)
# 训练模型
fit_kmeans = kmeans_model.fit(airline_scale)
# 查看聚类中心
print('K-Means聚类中心为：', kmeans_model.cluster_centers_, sep='\n')

K-Means聚类中心为：
[[ 0.05184321 -0.22680493 -0.00266815  2.19136467 -0.23125594]
 [ 0.48333235  2.48322162 -0.7993897   0.30863251  2.42474345]
 [ 1.16067608 -0.08691922 -0.37722423 -0.15590586 -0.09484481]
 [-0.7002121  -0.16114387 -0.41489162 -0.25513359 -0.16095881]
 [-0.31368082 -0.57402062  1.68627205 -0.1733275  -0.53682451]]


In [2]:
# 查看样本的类别标签
print('样本的类别标签为：', kmeans_model.labels_)

样本的类别标签为： [1 1 1 ... 3 4 4]


In [3]:
# 统计不同类别样本的数目
import pandas
r_A = pandas.Series(kmeans_model.labels_).value_counts()
print('最终每个类别的数目为：', r_A, sep='\n')

最终每个类别的数目为：
3    24659
2    15740
4    12125
1     5336
0     4184
dtype: int64
