# 任务2.2　掌握NumPy矩阵与通用函数

## 代码2-30　使用`mat`函数与`matrix`函数创建矩阵

In [1]:
import numpy
matrix1 = numpy.mat("1 2 3; 4 5 6; 7 8 9")
print('创建的矩阵为：', matrix1, sep='\n')

创建的矩阵为：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
matrix2 = numpy.matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print('创建的矩阵为：', matrix2, sep='\n')

创建的矩阵为：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 代码2-31　使用`bmat`函数创建矩阵

In [3]:
array1 = numpy.eye(3)
print('创建的数组1为：', array1, sep='\n')

创建的数组1为：
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
array2 = 3 * array1
print('创建的数组2为：', array2, sep='\n')

创建的数组2为：
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


In [5]:
print('创建的矩阵为：', numpy.bmat("array1 array2; array1 array2"), sep='\n')

创建的矩阵为：
[[1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]
 [1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]]


## 代码2-32　矩阵运算

In [6]:
matrix1 = numpy.mat("1 2 3; 4 5 6; 7 8 9")
print('创建的矩阵为：', matrix1, sep='\n')

创建的矩阵为：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
matrix2 = matrix1 * 3
print('创建的矩阵为：', matrix2, sep='\n')

创建的矩阵为：
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [8]:
print('矩阵相加结果为：', matrix1 + matrix2, sep='\n')

矩阵相加结果为：
[[ 4  8 12]
 [16 20 24]
 [28 32 36]]


In [9]:
print('矩阵相减结果为：', matrix1 - matrix2, sep='\n')

矩阵相减结果为：
[[ -2  -4  -6]
 [ -8 -10 -12]
 [-14 -16 -18]]


In [10]:
print('矩阵相乘结果为：', matrix1 * matrix2, sep='\n')

矩阵相乘结果为：
[[ 90 108 126]
 [198 243 288]
 [306 378 450]]


In [11]:
print('矩阵对应元素相乘结果为：', numpy.multiply(matrix1, matrix2), sep='\n')

矩阵对应元素相乘结果为：
[[  3  12  27]
 [ 48  75 108]
 [147 192 243]]


## 代码2-33　查看矩阵属性

　　在如下的例子中，矩阵`matrix1`是一个**奇异矩阵**，其**行列式**为$0$、**不可逆**。下面计算其逆矩阵会获得不可预料的结果。

In [12]:
print('矩阵转置结果为：', matrix1.T, sep='\n')

矩阵转置结果为：
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
# 实数的共轭就是其本身
print('矩阵共轭转置结果为：', matrix1.H, sep='\n')

矩阵共轭转置结果为：
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [14]:
print('矩阵的逆矩阵结果为：', matrix1.I, sep='\n')

矩阵的逆矩阵结果为：
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [15]:
print('矩阵的二维数组结果为：', matrix1.A, sep='\n')

矩阵的二维数组结果为：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 代码2-34　数组的四则运算

In [16]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 6])
print('数组相加结果为：', x + y)

数组相加结果为： [5 7 9]


In [17]:
print('数组相减结果为：', x - y)

数组相减结果为： [-3 -3 -3]


In [18]:
print('数组相乘结果为：', x * y)

数组相乘结果为： [ 4 10 18]


In [19]:
print('数组相处结果为：', x / y)

数组相处结果为： [0.25 0.4  0.5 ]


In [20]:
print('数组幂运算结果为：', x ** y)

数组幂运算结果为： [  1  32 729]


## 代码2-35　数组的比较运算

In [21]:
x = numpy.array([1, 3, 5])
y = numpy.array([2, 3, 4])
print('数组比较结果为：', x < y)

数组比较结果为： [ True False False]


In [22]:
print('数组比较结果为：', x > y)

数组比较结果为： [False False  True]


In [23]:
print('数组比较结果为：', x == y)

数组比较结果为： [False  True False]


In [24]:
print('数组比较结果为：', x >= y)

数组比较结果为： [False  True  True]


In [25]:
print('数组比较结果为：', x <= y)

数组比较结果为： [ True  True False]


In [26]:
print('数组比较结果为：', x != y)

数组比较结果为： [ True False  True]


## 代码2-36　数组的逻辑运算

In [27]:
print('数组的逻辑运算结果为：', numpy.all(x == y))

数组的逻辑运算结果为： False


In [28]:
print('数组逻辑运算结果为：', numpy.any(x == y))

数组逻辑运算结果为： True
