# 第6章　使用 `scikit-learn` 构建模型

## 任务6.1　使用 `sklearn` 转换器处理数据

<br>
<center>
    <b>代码6-1　加载<code>breast_cancer</code>数据集</b>
</center>

In [1]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
print('乳腺癌数据集的长度为：', len(cancer))
print('乳腺癌数据集的类型为：', type(cancer))

乳腺癌数据集的长度为： 6
乳腺癌数据集的类型为： <class 'sklearn.utils.Bunch'>


<br>
<center>
    <b>代码6-2　<code>sklearn</code>自带数据集内部信息获取</b>
</center>

In [2]:
cancer_data = cancer['data']
print('乳腺癌数据集的数据为：', cancer_data, sep='\n')

乳腺癌数据集的数据为：
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [3]:
cancer_target = cancer['target']
print('乳腺癌数据集的标签为：', cancer_target, sep='\n')

乳腺癌数据集的标签为：
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 

In [4]:
cancer_names = cancer['feature_names']
print('乳腺癌数据集的特征名为：', cancer_names, sep='\n')

乳腺癌数据集的特征名为：
['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [5]:
cancer_desc = cancer['DESCR']
print('乳腺癌数据集的描述信息为：', cancer_desc, sep='\n')

乳腺癌数据集的描述信息为：
.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is 

<br>
<center>
    <b>代码6-3　使用<code>train_test_split</code>划分数据集</b>
</center>

In [6]:
print('原始数据集数据的形状为：', cancer_data.shape)
print('原始数据集标签的形状为：', cancer_target.shape)

原始数据集数据的形状为： (569, 30)
原始数据集标签的形状为： (569,)


In [7]:
from sklearn.model_selection import train_test_split
(data_train, data_test, target_train, target_test) = train_test_split(
    cancer_data, cancer_target, test_size=0.2, random_state=42
)
print('训练集数据的形状为：', data_train.shape)
print('训练集标签的形状为：', target_train.shape)
print('测试集数据的形状为：', data_test.shape)
print('测试集数据的形状为：', target_test.shape)

训练集数据的形状为： (455, 30)
训练集标签的形状为： (455,)
测试集数据的形状为： (114, 30)
测试集数据的形状为： (114,)


<br>
<center>
    <b>代码6-4　离差标准化</b>
</center>

In [8]:
import numpy
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler().fit(data_train)
train_scaler = scaler.transform(data_train)
test_scaler = scaler.transform(data_test)
print('离差标准化前训练集数据的最小值为：', numpy.min(data_train))
print('离差标准化后训练集数据的最小值为：', numpy.min(train_scaler))
print('离差标准化前训练集数据的最大值为：', numpy.max(data_train))
print('离差标准化后训练集数据的最大值为：', numpy.max(train_scaler))
print('离差标准化前测试集数据的最小值为：', numpy.min(data_test))
print('离差标准化后测试集数据的最小值为：', numpy.min(train_scaler))
print('离差标准化前测试集数据的最大值为：', numpy.max(data_test))
print('离差标准化后测试集数据的最大值为：', numpy.max(train_scaler))

离差标准化前训练集数据的最小值为： 0.0
离差标准化后训练集数据的最小值为： 0.0
离差标准化前训练集数据的最大值为： 4254.0
离差标准化后训练集数据的最大值为： 1.0000000000000002
离差标准化前测试集数据的最小值为： 0.0
离差标准化后测试集数据的最小值为： 0.0
离差标准化前测试集数据的最大值为： 3432.0
离差标准化后测试集数据的最大值为： 1.0000000000000002


<br>
<center>
    <b>代码6-5　对<code>breast_cancer</code>数据集PCA降维</b>
</center>

In [9]:
from sklearn.decomposition import PCA
pca_model = PCA(n_components=10).fit(train_scaler)
train_PCA = pca_model.transform(train_scaler)
test_PCA = pca_model.transform(test_scaler)
print('PCA降维前训练集数据的形状为：', train_scaler.shape)
print('PCA降维后训练集数据的形状为：', train_PCA.shape)
print('PCA降维前测试集数据的形状为：', test_scaler.shape)
print('PCA降维后测试集数据的形状为：', test_PCA.shape)

PCA降维前训练集数据的形状为： (455, 30)
PCA降维后训练集数据的形状为： (455, 10)
PCA降维前测试集数据的形状为： (114, 30)
PCA降维后测试集数据的形状为： (114, 10)


<br>
<center>
    <b>代码6-6　获取<code>sklearn</code>自带的<code>boston</code>数据集</b>
</center>

In [10]:
from sklearn.datasets import load_boston
boston = load_boston()
boston_data = boston['data']
boston_target = boston['target']
boston_names = boston['feature_names']
print('波士顿房价数据集数据的形状为：', boston_data.shape)
print('波士顿房价数据集标签的形状为：', boston_target.shape)
print('波士顿房价数据集特征名的形状为：', boston_names.shape)

波士顿房价数据集数据的形状为： (506, 13)
波士顿房价数据集标签的形状为： (506,)
波士顿房价数据集特征名的形状为： (13,)


<br>
<center>
    <b>代码6-7　使用<code>train_test_split</code>划分<code>boston</code>数据集</b>
</center>

In [11]:
from sklearn.model_selection import train_test_split
(data_train, data_test, target_train, target_test) = train_test_split(
    boston_data, boston_target, test_size=0.2, random_state=42
)
print('训练集数据的形状为：', data_train.shape)
print('训练集标签的形状为：', target_train.shape)
print('测试集数据的形状为：', data_test.shape)
print('测试集标签的形状为：', target_test.shape)

训练集数据的形状为： (404, 13)
训练集标签的形状为： (404,)
测试集数据的形状为： (102, 13)
测试集标签的形状为： (102,)


<br>
<center>
    <b>代码6-8　使用<code>stdScale.transform</code>进行数据预处理</b>
</center>

In [12]:
from sklearn.preprocessing import StandardScaler
stdScale = StandardScaler().fit(data_train)
train_scaler = stdScale.transform(data_train)
test_scaler = stdScale.transform(data_test)
print('标准差标准化后训练集数据的方差为：', numpy.var(train_scaler))
print('标准差标准化后训练集数据的均值为：', numpy.mean(train_scaler))
print('标准差标准化后测试集数据的方差为：', numpy.var(test_scaler))
print('标准差标准化后测试集数据的均值为：', numpy.mean(test_scaler))

标准差标准化后训练集数据的方差为： 1.0
标准差标准化后训练集数据的均值为： 1.3637225393110834e-15
标准差标准化后测试集数据的方差为： 0.9474773930196593
标准差标准化后测试集数据的均值为： 0.030537934487192598


<br>
<center>
    <b>代码6-9　使用<code>pca.transform</code>进行PCA降维</b>
</center>

In [13]:
from sklearn.decomposition import PCA
pca = PCA(n_components=5).fit(train_scaler)
train_PCA = pca.transform(train_scaler)
test_PCA = pca.transform(test_scaler)
print('降维后波士顿房价数据集数据数据训练集的形状为：', train_PCA.shape)
print('降维后波士顿房价数据集数据数据测试集的形状为：', test_PCA.shape)

降维后波士顿房价数据集数据数据训练集的形状为： (404, 5)
降维后波士顿房价数据集数据数据测试集的形状为： (102, 5)
