# 任务2.3　利用`NumPy`进行统计分析

## 代码2-39　二进制数据存储

In [1]:
import numpy
array = numpy.arange(100).reshape(10, 10)
numpy.save("data/save_array", array)
print('保存的数据为：', array, sep='\n')

保存的数据为：
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


## 代码2-40　多个数组存储

In [2]:
array1 = numpy.array([[1, 2, 3], [4, 5, 6]])
array2 = numpy.arange(0, 1.0, 0.1)
numpy.savez('data/savez_array', array1, array2)
print('保存的数组1为：', array1, sep='\n')

保存的数组1为：
[[1 2 3]
 [4 5 6]]


In [3]:
print('保存的数组2为：', array2)

保存的数组2为： [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## 代码2-41　二进制文件读取

In [4]:
loaded_data = numpy.load("data/save_array.npy")
print('读取的数组为：', loaded_data, sep='\n')

读取的数组为：
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [5]:
loaded_data1 = numpy.load("data/savez_array.npz")
print('读取的数组1为：', loaded_data1['arr_0'], sep='\n')

读取的数组1为：
[[1 2 3]
 [4 5 6]]


In [6]:
print('读取的数组2为：', loaded_data1['arr_1'])

读取的数组2为： [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## 代码2-42　文件存储与读取

In [7]:
array = numpy.arange(0, 12, 0.5).reshape(4, -1)
print('创建的数组为：', array, sep='\n')

创建的数组为：
[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]


In [8]:
numpy.savetxt("data/array.csv", array, fmt="%d", delimiter=",")
loaded_data = numpy.loadtxt("data/array.csv", delimiter=",")
print('读取的数组为：', loaded_data, sep='\n')

读取的数组为：
[[ 0.  0.  1.  1.  2.  2.]
 [ 3.  3.  4.  4.  5.  5.]
 [ 6.  6.  7.  7.  8.  8.]
 [ 9.  9. 10. 10. 11. 11.]]


## 代码2-43　使用`genfromtxt`函数读取数组

In [9]:
loaded_data = numpy.genfromtxt("data/array.csv", delimiter=",")
print('读取的数组为：', loaded_data, sep='\n')

读取的数组为：
[[ 0.  0.  1.  1.  2.  2.]
 [ 3.  3.  4.  4.  5.  5.]
 [ 6.  6.  7.  7.  8.  8.]
 [ 9.  9. 10. 10. 11. 11.]]


## 代码2-44　使用`sort`函数进行排序

In [10]:
numpy.random.seed(42)
array = numpy.random.randint(1, 10, size=10)
print('创建的数组为：', array)

创建的数组为： [7 4 8 5 7 3 7 8 5 4]


In [11]:
array.sort()
print('排序后数组为：', array)

排序后数组为： [3 4 4 5 5 7 7 7 8 8]


In [12]:
array = numpy.random.randint(1, 10, size=(3, 3))
print('创建的数组为：', array)

创建的数组为： [[8 8 3]
 [6 5 2]
 [8 6 2]]


In [13]:
array.sort(axis=1)
print('排序后数组为：', array, sep='\n')

排序后数组为：
[[3 8 8]
 [2 5 6]
 [2 6 8]]


In [14]:
array.sort(axis=0)
print('排序后数组为：', array, sep='\n')

排序后数组为：
[[2 5 6]
 [2 6 8]
 [3 8 8]]


## 代码2-45　使用`argsort`函数进行排序

In [15]:
array = numpy.array([2, 3, 6, 8, 0, 7])
print('创建的数组为：', array)

创建的数组为： [2 3 6 8 0 7]


In [16]:
print('排序后数组为：', array.argsort())

排序后数组为： [4 0 1 2 5 3]


## 代码2-46　使用`lexsort`函数进行排序

In [17]:
a = numpy.array([3, 2, 6, 4, 5])
b = numpy.array([50, 30, 40, 20, 10])
c = numpy.array([400, 300, 600, 100, 200])
d = numpy.lexsort((a, b, c))
print('排序后数组为：', list(zip(a[d], b[d], c[d])))

排序后数组为： [(4, 20, 100), (5, 10, 200), (2, 30, 300), (3, 50, 400), (6, 40, 600)]


## 代码2-47　数组内数据去重

In [18]:
names = numpy.array(['小明', '小黄', '小花', '小明', '小花', '小兰', '小白'])
print('创建的数组为：', names)

创建的数组为： ['小明' '小黄' '小花' '小明' '小花' '小兰' '小白']


In [19]:
print('去重后的数组为：', numpy.unique(names))

去重后的数组为： ['小兰' '小明' '小白' '小花' '小黄']


In [20]:
# 与 nuique() 等价的传统Python
print('去重后的数组为：', sorted(set(names)))

去重后的数组为： ['小兰', '小明', '小白', '小花', '小黄']


In [21]:
ints = numpy.array([1, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8, 9, 10])
print('创建的数组为：', ints)

创建的数组为： [ 1  2  3  4  4  5  6  6  7  8  8  9 10]


In [22]:
print('去重后的数组为：', numpy.unique(ints))

去重后的数组为： [ 1  2  3  4  5  6  7  8  9 10]


## 代码2-48　使用`tile`函数实现数据重复

In [23]:
array = numpy.arange(5)
print('创建的数组为：', array)

创建的数组为： [0 1 2 3 4]


In [24]:
print('重复后数组为：', numpy.tile(array, 3))

重复后数组为： [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


## 代码2-49　使用`repeat`函数实现数据重复

In [25]:
numpy.random.seed(42)
array = numpy.random.randint(0, 10, size=(3, 3))
print('创建的数组为：', array, sep='\n')

创建的数组为：
[[6 3 7]
 [4 6 9]
 [2 6 7]]


In [26]:
print('重复后数组为：', array.repeat(2, axis=0), sep='\n')

重复后数组为：
[[6 3 7]
 [6 3 7]
 [4 6 9]
 [4 6 9]
 [2 6 7]
 [2 6 7]]


In [27]:
print('重复后数组为：', array.repeat(2, axis=1), sep='\n')

重复后数组为：
[[6 6 3 3 7 7]
 [4 4 6 6 9 9]
 [2 2 6 6 7 7]]


## 代码2-50　`NumPy`中常用统计函数的使用

In [28]:
array = numpy.arange(20).reshape(4, 5)
print('创建的数组为：', array, sep='\n')

创建的数组为：
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [29]:
print('数组的和为：', numpy.sum(array))

数组的和为： 190


In [30]:
print('数组纵轴的和为：', array.sum(axis=0))

数组纵轴的和为： [30 34 38 42 46]


In [31]:
print('数组横轴的和为：', array.sum(axis=1))

数组横轴的和为： [10 35 60 85]


In [32]:
print('数组的均值为：', numpy.mean(array))

数组的均值为： 9.5


In [33]:
print('数组纵轴的均值为：', array.mean(axis=0))

数组纵轴的均值为： [ 7.5  8.5  9.5 10.5 11.5]


In [34]:
print('数组横轴的均值为：', array.mean(axis=1))

数组横轴的均值为： [ 2.  7. 12. 17.]


In [35]:
print('数组的标准差为：', numpy.std(array))

数组的标准差为： 5.766281297335398


In [36]:
print('数组的方差为：', numpy.var(array))

数组的方差为： 33.25


In [37]:
print('数组的最小值为：', numpy.min(array))

数组的最小值为： 0


In [38]:
print('数组的最大值为：', numpy.max(array))

数组的最大值为： 19


In [39]:
print('数组的最小元素索引为：', numpy.argmin(array))

数组的最小元素索引为： 0


In [40]:
print('数组的最大元素索引为：', numpy.argmax(array))

数组的最大元素索引为： 19


## 代码2-51　`cumsum`函数和`cumprod`函数的使用

In [41]:
array = numpy.arange(2, 10)
print('创建的数组为：', array)

创建的数组为： [2 3 4 5 6 7 8 9]


In [42]:
print('数组元素的累计和为：', numpy.cumsum(array))

数组元素的累计和为： [ 2  5  9 14 20 27 35 44]


In [43]:
print('数组元素的累计积为：', numpy.cumprod(array))

数组元素的累计积为： [     2      6     24    120    720   5040  40320 362880]


## 代码2-52　花萼长度数据统计分析

&emsp;&emsp;`iris_sepal_length.csv`数据集存储于`sklearn.database`中，通过安装`sklearn`拓展包即可导入数据集进行使用。

In [44]:
from sklearn.datasets import load_iris
iris_sepal_length = load_iris()['data'][:, 0]
print('花萼长度表为：', iris_sepal_length, sep='\n')

花萼长度表为：
[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [45]:
iris_sepal_length.sort()
print('排序后的花萼长度表为：', iris_sepal_length, sep='\n')

排序后的花萼长度表为：
[4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9 4.9
 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.1 5.1 5.1 5.1
 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.2 5.2 5.3 5.4 5.4 5.4 5.4 5.4 5.4 5.5 5.5
 5.5 5.5 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.7 5.7 5.7 5.7
 5.7 5.8 5.8 5.8 5.8 5.8 5.8 5.8 5.9 5.9 5.9 6.  6.  6.  6.  6.  6.  6.1
 6.1 6.1 6.1 6.1 6.1 6.2 6.2 6.2 6.2 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3
 6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.5 6.5 6.5 6.5 6.5 6.6 6.6 6.7 6.7 6.7 6.7
 6.7 6.7 6.7 6.7 6.8 6.8 6.8 6.9 6.9 6.9 6.9 7.  7.1 7.2 7.2 7.2 7.3 7.4
 7.6 7.7 7.7 7.7 7.7 7.9]


In [46]:
print('去重后的花萼长度表为：', numpy.unique(iris_sepal_length))

去重后的花萼长度表为： [4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.
 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9]


In [47]:
print('花萼长度表的总和为：', numpy.sum(iris_sepal_length))

花萼长度表的总和为： 876.5


In [48]:
print('花萼长度表的累计和为：', numpy.cumsum(iris_sepal_length), sep='\n')

花萼长度表的累计和为：
[  4.3   8.7  13.1  17.5  22.   26.6  31.2  35.8  40.4  45.1  49.8  54.6
  59.4  64.2  69.   73.8  78.7  83.6  88.5  93.4  98.3 103.2 108.2 113.2
 118.2 123.2 128.2 133.2 138.2 143.2 148.2 153.2 158.3 163.4 168.5 173.6
 178.7 183.8 188.9 194.  199.1 204.3 209.5 214.7 219.9 225.2 230.6 236.
 241.4 246.8 252.2 257.6 263.1 268.6 274.1 279.6 285.1 290.6 296.1 301.7
 307.3 312.9 318.5 324.1 329.7 335.4 341.1 346.8 352.5 358.2 363.9 369.6
 375.3 381.1 386.9 392.7 398.5 404.3 410.1 415.9 421.8 427.7 433.6 439.6
 445.6 451.6 457.6 463.6 469.6 475.7 481.8 487.9 494.  500.1 506.2 512.4
 518.6 524.8 531.  537.3 543.6 549.9 556.2 562.5 568.8 575.1 581.4 587.7
 594.1 600.5 606.9 613.3 619.7 626.1 632.5 639.  645.5 652.  658.5 665.
 671.6 678.2 684.9 691.6 698.3 705.  711.7 718.4 725.1 731.8 738.6 745.4
 752.2 759.1 766.  772.9 779.8 786.8 793.9 801.1 808.3 815.5 822.8 830.2
 837.8 845.5 853.2 860.9 868.6 876.5]


In [49]:
print('花萼长度表的均值为：', numpy.mean(iris_sepal_length))

花萼长度表的均值为： 5.843333333333334


In [50]:
print('花萼长度表的标准差为：', numpy.std(iris_sepal_length))

花萼长度表的标准差为： 0.8253012917851409


In [51]:
print('花萼长度表的方差为：', numpy.var(iris_sepal_length))

花萼长度表的方差为： 0.6811222222222223


In [52]:
print('花萼长度表的最小值为：', numpy.min(iris_sepal_length))

花萼长度表的最小值为： 4.3


In [53]:
print('花萼长度表的最大值为：', numpy.max(iris_sepal_length))

花萼长度表的最大值为： 7.9
