# 实训2　创建一个国际象棋的棋盘

1. 训练要点
    1. 掌握矩阵创建方法
    2. 掌握数组索引的方法

2. 需求说明
    
    　　创建国际象棋棋盘，填充$8\times8$矩阵。国际象棋棋盘是个正方形，由横纵向个$8$格、颜色一深一浅交错排列的64个小方格组成，深色格为黑格，浅色格为白格，棋子就在这些格子中移动，如下图所示。

    ![国际象棋棋盘](img/Training2-2-1.jpg)

3. 实现思路及步骤
    1. 创建一个$8\times8$矩阵
    2. 将第1、3、5、7行和2、4、6列的元素设置为`True`。

In [1]:
# 导入NumPy程序包
import numpy

In [2]:
grid = numpy.zeros((8, 8), dtype=numpy.int)
for r in range(8):
    for c in range(8):
        if (r + c) % 2 == 0:
            grid[r, c] = 1
print('生成的棋盘为：', grid, sep='\n')

生成的棋盘为：
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
